### ISSUE TITLE
Can't parse timstamp from Hangouts.json?

### ISSUE THREAD

**Issue by bjodasso** [coandco/gtalk_export#4]
Processing json file at Hangouts.json
Traceback (most recent call last):
  File "gtalk_export.py", line 144, in <module>
    parse_json(args.json_location, args.name, args.email, args.timestamp_format)
  File "gtalk_export.py", line 99, in parse_json
    conversations = hangouts.hangoutsToArray(mydata, timestamp_format)
  File "hangouts.py", line 218, in hangoutsToArray
    messages.sort(cmp=lambda a,b: int(a['timestamp']) - int(b['timestamp']))
TypeError: comparison function must return int, not long

**Comment by coandco** [comment]
Try editing hangouts.py line 218 and changing this:
`messages.sort(cmp=lambda a,b: int(a['timestamp']) - int(b['timestamp']))`
to this:
`messages.sort(cmp=lambda a,b: int(int(a['timestamp']) - int(b['timestamp'])))`
